title: Hao Zhang's Home
email: me@hzhang.xyz
description: >
    Hello,  I am Hao Zhang, an undergraduate student from University of Science and Technology of China, majoring in Condensed Matter Physics.
github_username:  hzhangxyz

baseurl: ""
url: "https://hzhangxyz.github.io"

markdown: kramdown
theme: jekyll-theme-slate
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
